source 'https://rubygems.org'

gem 'foreman'
gem 'activesupport'
gem 'ruby-kafka'

# Specify your gem's dependencies in event-generator.gemspec
# gemspec
gem "rake", "~> 10.0"
gem "rspec", "~> 3.0"
gem "pry"
gem "webmock"

gemspec
